In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Importando dados da priori 29-nov-2021

In [14]:
#IMPORTS
import pandas as pd
pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : pt_BR.cp1252

pandas           : 1.3.4
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0.post20210125
Cython           : 0.29.23
pytest           : 6.2.3
hypothesis       : None
sphinx           : 4.0.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.8
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.9.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : 1.4.7
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.53.1

In [4]:
virtual = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=0)
cafi = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=1)
cbar = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=2)
cbja = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=3)
cgar = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=4)
cpes = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=5)
cplt = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=6)
reipe = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=7)
cabl = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=8)
ccsa = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=9)
cigr = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=10)
cipj = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=11)
cjbg = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=12)
cprm = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=13)
crec = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=14)
ccar = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=15)
coli = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=16)
cvsa = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=17)

# anexo_tres = pd.read_excel('priori/Anexo III rev1.xlsx')
# anexo_quatro = pd.read_excel('priori/Anexo IV rev1.xlsx')
# anexo_cinco = pd.read_excel('priori/Anexo V.xlsx')
# anexo_vir = pd.read_excel('priori/Virtuais.xlsx')
# anexo_seis = pd.read_excel('priori/Anexo VI rev1.xlsx')

# Importando dados priori 06-out-2021

In [5]:
abr = pd.read_excel('2021-10-08-priori/ABR.xlsx')
afi = pd.read_excel('2021-10-08-priori/AFI.xlsx')
bar = pd.read_excel('2021-10-08-priori/BAR.xlsx')
bja = pd.read_excel('2021-10-08-priori/BJA.xlsx')
cab = pd.read_excel('2021-10-08-priori/CAB.xlsx')
car = pd.read_excel('2021-10-08-priori/CAR.xlsx')
gar = pd.read_excel('2021-10-08-priori/GAR.xlsx')
iga = pd.read_excel('2021-10-08-priori/IGA.xlsx')
ipj = pd.read_excel('2021-10-08-priori/IPJ.xlsx')
jab = pd.read_excel('2021-10-08-priori/JAB.xlsx')
oli = pd.read_excel('2021-10-08-priori/OLI.xlsx')
pes = pd.read_excel('2021-10-08-priori/PES.xlsx')
plt = pd.read_excel('2021-10-08-priori/PLT.xlsx')
prm = pd.read_excel('2021-10-08-priori/PRM.xlsx')
rec = pd.read_excel('2021-10-08-priori/REC.xlsx')
rei = pd.read_excel('2021-10-08-priori/REI.xlsx')
vsa = pd.read_excel('2021-10-08-priori/VSA.xlsx')
vir = []

In [6]:
dicionario = {len(abr):len(cabl), len(afi):len(cafi), len(bar):len(cbar), len(bja):len(cbja), len(cab):len(ccsa) , len(car):len(ccar), len(gar):len(cgar), len(iga):len(cigr),
              len(ipj):len(cipj), len(jab):len(cjbg), len(oli):len(coli), len(pes):len(cpes), len(plt):len(cplt), len(prm):len(cprm), len(rec):len(crec), len(rei):len(reipe),
              len(vsa):len(cvsa), len(vir):len(virtual)}
campus = ['CABL', 'CAFI', 'CBAR', 'CBJA', 'CCSA', 'CCAR', 'CGAR', 'CIGR', 'CIPJ', 'CJBG', 'COLI', 'CPES', 'CPLT', 'CPRM', 'CREC', 'REIPE', 'CVSA', 'VIRTUAL']

In [7]:
print(dicionario)

{2905: 2907, 8354: 8355, 8234: 8124, 7211: 7194, 7472: 7572, 4713: 4750, 8866: 8862, 3374: 3182, 8612: 8630, 2641: 2621, 2992: 2989, 9519: 9569, 4620: 4619, 1935: 1943, 34587: 33659, 7482: 7752, 15069: 15283, 0: 58}

In [8]:
salas = pd.read_excel('priori/Anexo III rev2.xlsx', sheet_name=19)

In [9]:
quant = pd.DataFrame(list(dicionario.items()), columns=['priori-06-out-2021', 'priori-29-nov-2021'])
quant['campi'] = campus
quant = quant[['campi',  'priori-06-out-2021', 'priori-29-nov-2021']]
quant['diferenca'] = quant['priori-06-out-2021'] - quant['priori-29-nov-2021']
total1 = quant['priori-06-out-2021'].sum()
total2 = quant['priori-29-nov-2021'].sum()
print(total1)
print(total2)

total = {'campi':'TOTAL', 'priori-06-out-2021':total1, 'priori-29-nov-2021':total2, 'diferenca':total1-total2}
quant = quant.append(total, ignore_index=True)

display(quant)
quant.to_excel('quantificacoes/quantificacao_priori.xlsx', index=False)

138586
138069

      campi  priori-06-out-2021  priori-29-nov-2021  diferenca
0      CABL                2905                2907         -2
1      CAFI                8354                8355         -1
2      CBAR                8234                8124        110
3      CBJA                7211                7194         17
4      CCSA                7472                7572       -100
5      CCAR                4713                4750        -37
6      CGAR                8866                8862          4
7      CIGR                3374                3182        192
8      CIPJ                8612                8630        -18
9      CJBG                2641                2621         20
10     COLI                2992                2989          3
11     CPES                9519                9569        -50
12     CPLT                4620                4619          1
13     CPRM                1935                1943         -8
14     CREC               34587               33659        928
15    REIPE                7482                7752       -270
16     CVSA               15069               15283       -214
17  VIRTUAL                   0                  58        -58
18    TOTAL              138586              138069        517

In [10]:
nome_local = salas['Nome Local'].drop_duplicates()
local = salas['Local'].drop_duplicates()
nome_local.to_excel('quantificacoes/quantificacoes_salas.xlsx', index=False)
print(local)

0                 REC Recife
8                 CAB - Cabo
10             IPJ - Ipojuca
55                       REI
71             CAR - Caruaru
72              OLI - Olinda
188            VIT - Vitoria
244          PES - Pesqueira
344        BAR - Barreiros
978       BEJ - Belo Jardim
2113      ABL - Abreu e Lima
3084         IGR - Iguarassu
3262         AFI - Afogados
4481        GAR - Garanhuns
5185          PLT - Paulista
6143          PMR - Palmares
9149          JBO - Jaboatão
138011                   NaN
Name: Local, dtype: object

In [11]:
nao_localizados = pd.read_excel('priori/Anexo IV rev1.xlsx')
display(nao_localizados)

,id,numero,num novo,Ativo,descricao,Estado do bem,Nome do custo,Nome Local,Local,Responsável,...,Depreciação Mensal,Depreciação Anual,Taxa Válida MCASP (%),Valor residual - Vida útil (Anos) MCASP,Valor residual - Vida útil (Anos) MCASP - R$,Amort/Depre. Calculdada Apurada,Valor Contábil Líquido Apurado,Valor Justo,Valor Pesquisa,Fonte da Pesquisa
0,2,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000083,NaN,0.1,10,0.001,NaN,NaN,NaN,199.0,https://www.enjoei.com.br/p/poltrona-em-tecido...
1,3,3,NaN,3,13CREC - MESA (PARA REUNIAO MED 125 X 74CM MAD...,NaN,NaN,NaN,NaN,NaN,...,0.000083,NaN,0.1,10,0.001,NaN,NaN,NaN,290.0,https://produto.mercadolivre.com.br/MLB-162365...
2,6,6,NaN,6,21CREC - POLTRONA GIRATORIA (REGUL C/ROD ESTRU...,NaN,NaN,NaN,NaN,NaN,...,0.000083,NaN,0.1,10,0.001,NaN,NaN,NaN,200.0,https://produto.mercadolivre.com.br/MLB-841720...
3,7,7,NaN,7,23CREC - POLTRONA GIRATORIA (REGUL C/ROD ESTRU...,NaN,NaN,NaN,NaN,NaN,...,0.000083,NaN,0.1,10,0.001,NaN,NaN,NaN,200.0,https://produto.mercadolivre.com.br/MLB-841720...
4,9,9,NaN,9,25CREC - MESA (LINHA MULTIPLA M-11 KASTRUP EM ...,NaN,NaN,NaN,NaN,NaN,...,0.000083,NaN,0.1,10,0.001,NaN,NaN,NaN,743.0,https://produto.mercadolivre.com.br/MLB-867498...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115974,261703,258510,NaN,258510,"SCANNER, tipo 3D, cromatismo policromático, ti...",NaN,NaN,NaN,NaN,NaN,...,191.666667,NaN,0.1,5,575.000,NaN,NaN,NaN,250.0,https://produto.mercadolivre.com.br/MLB-126816...
115975,261754,258561,NaN,258561,NaN,NaN,NaN,NaN,NaN,NaN,...,4.996250,NaN,0.1,10,59.955,NaN,NaN,NaN,99.0,https://produto.mercadolivre.com.br/MLB-173727...
115976,261755,258562,NaN,258562,NaN,NaN,NaN,NaN,NaN,NaN,...,4.996250,NaN,0.1,10,59.955,NaN,NaN,NaN,99.0,https://produto.mercadolivre.com.br/MLB-173727...
115977,261756,258563,NaN,258563,NaN,NaN,NaN,NaN,NaN,NaN,...,4.996250,NaN,0.1,10,59.955,NaN,NaN,NaN,99.0,https://produto.mercadolivre.com.br/MLB-173727...
115978,261757,258564,NaN,258564,NaN,NaN,NaN,NaN,NaN,NaN,...,4.996250,NaN,0.1,10,59.955,NaN,NaN,NaN,99.0,https://produto.mercadolivre.com.br/MLB-173727...

In [12]:
nao_localizados.info()
nao_localizados = nao_localizados[['id', 'numero', 'Ativo', 'descricao', 'categoria_codigo', 'conta_contabil_codigo', 'status2', 'Valor Pesquisa', ]]
nao_localizados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115979 entries, 0 to 115978
Data columns (total 48 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   id                                            115979 non-null  int64
 1   numero                                        115979 non-null  int64
 2   num novo                                      0 non-null       float64
 3   Ativo                                         115979 non-null  int64
 4   descricao                                     96869 non-null   object
 5   Estado do bem                                 0 non-null       float64
 6   Nome do custo                                 0 non-null       float64
 7   Nome Local                                    0 non-null       float64
 8   Local                                         0 non-null       float64
 9   Responsável                                   0 non-null       float64
 10  Status                                        115979 non-null  object
 11  categoria_codigo                              115979 non-null  object
 12  categoria_nome                                115979 non-null  object
 13  conta_contabil_codigo                         115979 non-null  int64
 14  conta_contabil                                115979 non-null  object
 15  status2                                       115979 non-null  object
 16  numeroserie                                   656 non-null     object
 17  Descrição                                     115979 non-null  object
 18  Coluna1                                       115979 non-null  object
 19   -                                            31308 non-null   object
 20  Coluna2                                       19191 non-null   object
 21  Coluna3                                       5543 non-null    object
 22  Coluna4                                       2234 non-null    object
 23  Coluna5                                       1000 non-null    object
 24  Coluna6                                       473 non-null     object
 25  sala                                          123 non-null     object
 26  sala_predio                                   58 non-null      object
 27  data_entrada                                  46 non-null      object
 28  data_da_carga                                 35 non-null      object
 29  responsavel_atual                             3 non-null       float64
 30  resposavel_setor                              1 non-null       float64
 31  campus_da_carga                               1 non-null       float64
 32  nota_fiscal                                   1 non-null       float64
 33  fornecedor_entrada                            1 non-null       float64
 34  valor                                         1 non-null       object
 35  AAA                                           0 non-null       float64
 36  Ano                                           115979 non-null  int64
 37  Valor Residual (5%) - Mercado                 115979 non-null  float64
 38  Depreciação Mensal                            115014 non-null  float64
 39  Depreciação Anual                             0 non-null       float64
 40  Taxa Válida MCASP (%)                         115979 non-null  float64
 41  Valor residual - Vida útil (Anos) MCASP       115979 non-null  int64
 42  Valor residual - Vida útil (Anos) MCASP - R$  115979 non-null  float64
 43  Amort/Depre. Calculdada Apurada               0 non-null       float64
 44  Valor Contábil Líquido Apurado                0 non-null       float64
 45  Valor Justo                                   1 non-null       float64
 46  Valor Pesquisa                                115979 non-null  float64
 47  Fonte da Pesquisa                             115978 non-null  object
dtypes: float64(21), int64(6), object(21)
memory usage: 42.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115979 entries, 0 to 115978
Data columns (total 8 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   id                     115979 non-null  int64
 1   numero                 115979 non-null  int64
 2   Ativo                  115979 non-null  int64
 3   descricao              96869 non-null   object
 4   categoria_codigo       115979 non-null  object
 5   conta_contabil_codigo  115979 non-null  int64
 6   status2                115979 non-null  object
 7   Valor Pesquisa         115979 non-null  float64
dtypes: float64(1), int64(4), object(3)
memory usage: 7.1+ MB

In [13]:
virtuais = pd.read_excel('priori/Virtuais.xlsx')

virtual.info()
virtuais.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 41 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            58 non-null     int64
 1   numero                                        58 non-null     int64
 2   Etiqueta                                      58 non-null     object
 3   Ativo                                         58 non-null     int64
 4   Descricao                                     58 non-null     object
 5   Estado do bem                                 58 non-null     object
 6   Nome do custo                                 58 non-null     object
 7   Nome Local                                    58 non-null     object
 8   Local                                         58 non-null     object
 9   Responsável                                   0 non-null      float64
 10  Status                                        58 non-null     object
 11  categoria_codigo                              58 non-null     object
 12  categoria_nome                                58 non-null     object
 13  conta_contabil_codigo                         58 non-null     int64
 14  conta_contabil                                58 non-null     object
 15  status2                                       58 non-null     object
 16  numeroserie                                   0 non-null      float64
 17  descricao2                                    58 non-null     object
 18  sala                                          0 non-null      float64
 19  sala_predio                                   0 non-null      float64
 20  data_entrada                                  58 non-null     object
 21  data_da_carga                                 58 non-null     object
 22  responsavel_atual                             58 non-null     object
 23  resposavel_setor                              58 non-null     object
 24  campus_da_carga                               58 non-null     object
 25  nota_fiscal                                   19 non-null     float64
 26  fornecedor_entrada                            58 non-null     object
 27  Valor - R$                                    58 non-null     int64
 28  AAA                                           0 non-null      float64
 29  Ano                                           58 non-null     int64
 30  Valor Residual (5%) - Mercado                 58 non-null     float64
 31  Depreciação Mensal                            58 non-null     float64
 32  Depreciação Anual                             0 non-null      float64
 33  Amort/Depre. Calculdada Apurada               58 non-null     float64
 34  Valor Contábil Líquido Apurado                58 non-null     float64
 35  Taxa Válida MCASP (%)                         58 non-null     float64
 36  Valor residual - Vida útil (Anos) MCASP       58 non-null     int64
 37  Valor residual - Vida útil (Anos) MCASP - R$  58 non-null     float64
 38  Valor Justo                                   58 non-null     int64
 39  Valor Pesquisa                                58 non-null     int64
 40  Fonte da Pesquisa                             58 non-null     object
dtypes: float64(13), int64(9), object(19)
memory usage: 18.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 41 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            58 non-null     int64
 1   numero                                        58 non-null     int64
 2   num novo                                      58 non-null     object
 3   Ativo                                         58 non-null     int64
 4   Descricao                                     58 non-null     object
 5   Estado do bem                                 58 non-null     object
 6   Nome do custo                                 58 non-null     object
 7   Nome Local                                    58 non-null     object
 8   Local                                         58 non-null     object
 9   Responsável                                   0 non-null      float64
 10  Status                                        58 non-null     object
 11  categoria_codigo                              58 non-null     object
 12  categoria_nome                                58 non-null     object
 13  conta_contabil_codigo                         58 non-null     int64
 14  conta_contabil                                58 non-null     object
 15  status2                                       58 non-null     object
 16  numeroserie                                   0 non-null      float64
 17  descricao2                                    58 non-null     object
 18  sala                                          0 non-null      float64
 19  sala_predio                                   0 non-null      float64
 20  data_entrada                                  58 non-null     object
 21  data_da_carga                                 58 non-null     object
 22  responsavel_atual                             58 non-null     object
 23  resposavel_setor                              58 non-null     object
 24  campus_da_carga                               58 non-null     object
 25  nota_fiscal                                   19 non-null     float64
 26  fornecedor_entrada                            58 non-null     object
 27  Valor - R$                                    58 non-null     int64
 28  AAA                                           0 non-null      float64
 29  Ano                                           58 non-null     int64
 30  Valor Residual (5%) - Mercado                 58 non-null     float64
 31  Depreciação Mensal                            58 non-null     float64
 32  Depreciação Anual                             0 non-null      float64
 33  Amort/Depre. Calculdada Apurada               58 non-null     float64
 34  Valor Contábil Líquido Apurado                58 non-null     float64
 35  Taxa Válida MCASP (%)                         58 non-null     float64
 36  Valor residual - Vida útil (Anos) MCASP       58 non-null     int64
 37  Valor residual - Vida útil (Anos) MCASP - R$  58 non-null     float64
 38  Valor Justo                                   58 non-null     int64
 39  Valor Pesquisa                                58 non-null     int64
 40  Fonte da Pesquisa                             58 non-null     object
dtypes: float64(13), int64(9), object(19)
memory usage: 18.7+ KB